[build]
  command = "bun run db:generate && bun run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**", "generated/**", "prisma/**", "package.json"]

